### ISSUE TITLE
加上pjax后，无法使用Dplayer

### ISSUE THREAD

**Issue by 690688037** [idawnlight/typecho-theme-material#100]
那个回调函数不知道怎么放，求指教！

**Comment by idawnlight** [comment]
很抱歉，PJAX 不是这个主题原生支持的功能，对此我无法提供帮助。

**Comment by wanghaojie98** [comment]
不好意思，这个我也不会。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月13日(周五) 凌晨1:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [idawnlight/typecho-theme-material] 加上pjax后，无法使用Dplayer (Issue #100)




 
那个回调函数不知道怎么放，求指教！
