### ISSUE TITLE
能否添加materail手势？

### ISSUE THREAD

**Issue by mysteriouseye** [idawnlight/typecho-theme-material#16]
大佬您好 我现在一直在用您的模板
我本人不熟悉material  反馈一个建议，很多materail设计其实都有侧边栏手势划出，手指在边缘向右滑滑出
希望您的模板能越来越好

**Comment by LiMingYuGuang** [comment]
此分支将尽可能跟随 viosey/hexo-theme-material，因此不会主动进行较大改动
您可以前往 viosey/hexo-theme-material 请求此特性，上游更新后我将尽快合并
