### ISSUE TITLE
我编辑外观的时候说我数据库错误

### ISSUE THREAD

**Issue by Nightiswatch** [idawnlight/typecho-theme-material#17]

**Comment by LiMingYuGuang** [comment]
主题文件夹名称是否已更改为 “Material” ？

**Comment by PascalYuxian** [comment]
最新3.2.5，文件夹修改后同提示数据库出错，更换其他主题再换会问题依旧

**Comment by idawnlight** [comment]
请在 `config.inc.php` 添加一行 `define('__TYPECHO_DEBUG__', true);` 重新启用主题，将报错页发送给我

________________________________
Sent from YoMail<http://www.yomail.com/?utm_source=signature>

发件人： PascalYuxian<mailto:notifications@github.com>
发送时间： 2018-10-02 09:13:20
收件人：  idawnlight/typecho-theme-material<mailto:typecho-theme-material@noreply.github.com>
抄送：  黎明余光<mailto:idawn@live.com>; State change<mailto:state_change@noreply.github.com>
主题： Re: [idawnlight/typecho-theme-material] 我编辑外观的时候说我数据库错误 (#17)

最新3.2.5，文件夹修改后同提示数据库出错，更换其他主题再换会问题依旧

**Comment by PascalYuxian** [comment]
强制重新刷新后问题已解决，缓存背锅

黎明余光 <notifications@github.com> 于 2018年10月2日周二 09:30写道：
