### ISSUE TITLE
文章评论分享按钮弹出菜单显示不全

### ISSUE THREAD

**Issue by BBleae** [idawnlight/typecho-theme-material#19]
![image](https://user-images.githubusercontent.com/13044102/32733187-8dd36b6c-c8c9-11e7-8bb4-6a321beb1406.png)

**Comment by LiMingYuGuang** [comment]
这是个已知 bug
你问我怎么解决，我也不知道啊（逃

**Comment by Xiaopika** [comment]
哈哈哈哈能不能让这个C框体处于B框体上层，调整div行不行？（纯小白

![qq 20171209014046](https://user-images.githubusercontent.com/10910848/33778151-666a8dd6-dc82-11e7-87b2-59e56b77cbea.jpg)

**Comment by LiMingYuGuang** [comment]
@Xiaopika 那你试试啊，成功记得给我提个 PR，毕竟我对 CSS 基本懵逼（

**Comment by xtlsoft** [comment]
调整弹出框的z-index，例如到99999.

**Comment by LiMingYuGuang** [comment]
@xtlsoft 没用，下一个

**Comment by memset0** [comment]
好像viosey的hexo主题本来就有这个bug

**Comment by idawnlight** [comment]
@memset0 是的，包括评论区域下面的留白应该是为了在某种程度上规避这个 bug，然后 Hexo 直接把评论删了不管这 bug 了，我也很无奈啊

**Comment by zp324511** [comment]
overflow 设置成 hidden

**Comment by bbaa-bbaa** [comment]
@zp324511 厉害了亲测可用

**Comment by idawnlight** [comment]
@bbaa-bbaa 大佬们给我发个 pr
