### ISSUE TITLE
默认 cdn (jsdelivr) 过慢

### ISSUE THREAD

**Issue by 9ii** [idawnlight/typecho-theme-material#23]
`jsdelivr` 在部分地区延时过高，建议改为 Bootrap 的 CDN。

**Comment by LiMingYuGuang** [comment]
jsdelivr 在国内使用 QUANTIL 作为 CDN，国外同时接入三家国际 CDN，在全球范围内有优秀的访问速度
BootCDN 在国外访问速度仅为一般，并且不包含 Material 所需的所有库，因此不会使用 BootCDN 来替代 jsdelivr
