### ISSUE TITLE
设置外观里的新版本提示有偏差（

### ISSUE THREAD

**Issue by Rowingbohe** [idawnlight/typecho-theme-material#24]
![_ _20180127204406](https://user-images.githubusercontent.com/31030701/35472348-7abe1bf2-03a8-11e8-9b88-4f91e340ab47.png)
顺便提一下这个主题真的好看，至少逼格很高（？？？），感谢作者！

**Comment by Xiaopika** [comment]
大概是 preview 预览版和正式版的区别呢~
