### ISSUE TITLE
建议增加搜索栏字体颜色更改选项

### ISSUE THREAD

**Issue by ajcxsu** [idawnlight/typecho-theme-material#26]
由于背景图片的缘故，如果搜索栏的背景为透明而图片又为深色，那么搜索栏就很难看清
如果作者能增加的话就最好了\_(:зゝ∠)_

**Comment by bbaa-bbaa** [comment]
@idawnlight 这个在pull里也加了- -

**Comment by idawnlight** [comment]
emmm，好像手滑发错了一条评论
