### ISSUE TITLE
使用中的一些小问题

### ISSUE THREAD

**Issue by huipeng8** [idawnlight/typecho-theme-material#27]
**很喜欢这个风格的主题，感谢作者。但是使用时还有一些小问题，不知道是不是我配置的问题**

1. 自带的搜索功能没法使用....

2. 留言填写完成后就没有了...

3. 主题设定没法保存，切换主题后就没了...

**Comment by idawnlight** [comment]
1. 好像是个不小的 bug，试着修一下
2. 尝试关闭 Typecho 的反垃圾
3. 这是 Typecho 自身的问题，只会保存一个主题的配置，无法解决
