### ISSUE TITLE
背景能否实现调整显示样式？总有一部分显示不出来

### ISSUE THREAD

**Issue by Rowingbohe** [idawnlight/typecho-theme-material#29]
比如说可以选择平铺，或者宽对齐高对齐一类的，我这里
![61caae05-3a30-48ab-88ff-c73bae76b4ca](https://user-images.githubusercontent.com/31030701/37870518-ab6cff46-300a-11e8-8dd0-87ba90154ab8.jpeg)
这样完整的图上传成背景变成
![5a0eeab3-bece-4b79-88b4-4be54e66c6f3](https://user-images.githubusercontent.com/31030701/37870523-ca9e610c-300a-11e8-9ef2-0f0b359affdf.png)
这样，右边一部分显示不出来。

**Comment by idawnlight** [comment]
感觉改显示方式问题会更多...有需要还是自己本地改一下吧，或者给我提个 PR 也行
