### ISSUE TITLE
文章缩略图无法正常显示

### ISSUE THREAD

**Issue by HelloLingC** [idawnlight/typecho-theme-material#31]
网址:https://lcblog.cn
没有配置缩略图这方面
从一开始就没有动过，刚安装的模板

**Comment by idawnlight** [comment]
初步判定 Lazyload 失效，疑似无用的 `Like` 插件带来重复的 jQuery 加载导致 Lazyload 初始化失败，请尝试禁用任何多余的插件并逐一排查
