### ISSUE TITLE
我无法点开文章

### ISSUE THREAD

**Issue by dtaliy** [idawnlight/typecho-theme-material#36]
我的博客地址:ywl.tn
无法点开文章

使用的是dokcer搭建的环境
php7.2
mysql5.7
ngnix

docker-compose.yml文件内容：

version: '2'
services:
  nginx:
    image: nginx:1.13.9-alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./typecho:/app
      - ./typecho.conf:/etc/nginx/conf.d/default.conf
      - logs:/var/log/nginx
    links:
      - php-fpm
    depends_on:
      - php-fpm
  php-fpm:
    image: myphp/php-7.2.3
    restart: always
    volumes:
      - ./typecho:/app
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7.21
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - logs:/var/logs/mysql
    env_file:
      - mysql.env
volumes:
  logs:

typecho版本是开发版本

**Comment by idawnlight** [comment]
初步判断为 Typecho 开发版的 bug，请更换稳定版查看能否复现
![22518b04-b085-4753-8938-cf3b2d6cf9f2](https://user-images.githubusercontent.com/18070833/41416753-24bb8c16-701e-11e8-9b86-d0993628dc90.png)

**Comment by dtaliy** [comment]
![qq 20180614225817](https://user-images.githubusercontent.com/24987101/41420169-7703060e-7026-11e8-9908-56ae610aacfa.png)
还是这样，我这次用的是最新版了

**Comment by xtlsoft** [comment]
1. 你并没有使用 Material 主题。
2. 黎明并没有义务回答 Typecho 有关issue，请去Typecho下面提交。
3. 黎明在中考，有问题暂时回避。

发送自 Windows 10 版邮件应用

发件人: dtaliy
发送时间: 2018年6月14日 23:00
收件人: idawnlight/typecho-theme-material
抄送: Subscribed
主题: Re: [idawnlight/typecho-theme-material] 我无法点开文章 (#36)


还是这样，我这次用的是最新版了
