### ISSUE TITLE
话说本地搜索框的大小是不是太小了点

### ISSUE THREAD

**Issue by bbaa-bbaa** [idawnlight/typecho-theme-material#37]
![img](https://bbaass.tk/static/img/1.png)
如题....

**Comment by idawnlight** [comment]
你这啥设备啊...
![default](https://user-images.githubusercontent.com/18070833/41505390-1b560ed4-723b-11e8-8e9f-2f17a12f595d.png)

**Comment by bbaa-bbaa** [comment]
标题和内容太短没把他撑开...
