### ISSUE TITLE
更新到3.2.1

### ISSUE THREAD

**Issue by 1156496364** [idawnlight/typecho-theme-material#38]
那个文章中的二维码失效了

**Comment by idawnlight** [comment]
已在 master 分支解决此问题，如需解决请下载更新

**Comment by bbaa-bbaa** [comment]
@idawnlight
话说你有没有javascript的原代码
很多都混淆过诶

**Comment by idawnlight** [comment]
@bbaa-bbaa 然而我也不知道 viosey 到底对 js 做了啥...
`Material_js` 那一块像是对 MDL 的源代码混淆后又格式化的，然后还有一点修改...
