### ISSUE TITLE
希望能加入文章目录

### ISSUE THREAD

**Issue by 52TKG** [idawnlight/typecho-theme-material#40]
一直在用这个主题，非常好看，但是美中不足的是没有文章目录。访问网站的时候如果有一个文章目录，可以让游客对网站所有文章一目了然，这是个不错的功能，希望大佬能加入归档文章目录，谢谢

**Comment by idawnlight** [comment]
是否指 `撰写->创建页面->自定义模板` 中的时间轴归档？

![default](https://user-images.githubusercontent.com/18070833/41892519-f8a8bfb4-794a-11e8-8f0a-669a65d8bea2.png)

**Comment by 52TKG** [comment]
原来已经有啦，哈哈，藏得好深，谢谢
