### ISSUE TITLE
highlight替换style

### ISSUE THREAD

**Issue by gaocong0511** [idawnlight/typecho-theme-material#42]
我使用了大佬的主题，非常好用！感谢
请问大佬~我想替换一下你highlight.js的style的css文件  可是替换之后显示不是很正常  我替换的是css目录下面的 highlight.min.css  
![image](https://user-images.githubusercontent.com/36976079/42740479-953fc63a-88da-11e8-90e5-e9aceca1cb8b.png)
结果换完之后成这样了 感觉像是背景颜色没有正常显示 大佬可否告诉我我还需要修改哪里吗？
实际应该是这样的
![image](https://user-images.githubusercontent.com/36976079/42740555-a8a5e064-88db-11e8-9889-74c7d3943f1f.png)

**Comment by gaocong0511** [comment]
/**
 * Obsidian style
 * ported by Alexander Marenin (http://github.com/ioncreature)
 */

.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: #282b2e;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-literal,
.hljs-selector-id {
  color: #93c763;
}

.hljs-number {
  color: #ffcd22;
}

.hljs {
  color: #e0e2e4;
}

.hljs-attribute {
  color: #668bb0;
}

.hljs-code,
.hljs-class .hljs-title,
.hljs-section {
  color: white;
}

.hljs-regexp,
.hljs-link {
  color: #d39745;
}

.hljs-meta {
  color: #557182;
}

.hljs-tag,
.hljs-name,
.hljs-bullet,
.hljs-subst,
.hljs-emphasis,
.hljs-type,
.hljs-built_in,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-addition,
.hljs-variable,
.hljs-template-tag,
.hljs-template-variable {
  color: #8cbbad;
}

.hljs-string,
.hljs-symbol {
  color: #ec7600;
}

.hljs-comment,
.hljs-quote,
.hljs-deletion {
  color: #818e96;
}

.hljs-selector-class {
  color: #A082BD
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-literal,
.hljs-doctag,
.hljs-title,
.hljs-section,
.hljs-type,
.hljs-name,
.hljs-strong {
  font-weight: bold;
}
忘记贴css了 不好意思大佬

**Comment by idawnlight** [comment]
感谢反馈，确定这锅应该由 viosey 来背...

**Comment by gaocong0511** [comment]
我换了pre这个标签有关的css的背景可以了 嘿嘿
