### ISSUE TITLE
渐变背景变成白色

### ISSUE THREAD

**Issue by PascalYuxian** [idawnlight/typecho-theme-material#48]
更新 主题至3.2.0之后，我两个站点的渐变背景不知为何变为白色，经多次修改设置，调试无果，前来请求帮助

**Comment by idawnlight** [comment]
这是 3.2.0 的已知 bug，请尝试更新至 3.2.2，查看十分恢复

**Comment by PascalYuxian** [comment]
问题已解决，更新3.2.2后背景仍是白色，切换其他主题，再切换回来就为渐变了 😂
