### ISSUE TITLE
首页不能滑动浏览及缩略图有问题

### ISSUE THREAD

**Issue by baihouzi** [idawnlight/typecho-theme-material#49]
pc端访问时首页不能往下滑动，移动端访问时虽可以滑动但是划一下就卡一下；还有缩略图，我设置的显示文章第一张图，主题刚启用时没问题，刷新了两次，缩略图就变成了纯色蓝色，请问是我设置的问题还是bug呢？

**Comment by idawnlight** [comment]
请给出示例站点链接
