### ISSUE TITLE
关闭localstorage的问题

### ISSUE THREAD

**Issue by hiCasper** [idawnlight/typecho-theme-material#51]
localstorage在某些情况下不太好用..如果需要关闭的话，直接将js部分css/jslsloader的函数换成正常引入就好了吗？

顺便请教一下，pjax是否可以手动关闭，感觉对评论不太友好

**Comment by idawnlight** [comment]
localstorage 已经在计划提供选开关了
并且这个主题并没有 pjax...

**Comment by idawnlight** [comment]
localstorage 现已可以被关闭
