### ISSUE TITLE
评论为空跳转新页面

### ISSUE THREAD

**Issue by 1292778464** [idawnlight/typecho-theme-material#52]
这个可以去掉吗?改用抖动提示
再限制一下头图大小，看着不是一样的
评论之后不会自动刷新
文章页脚加入谷歌广告，当无广告时会重新加载一次主页，禁忌，多重存在

**Comment by idawnlight** [comment]
1. 不能
2. 请具体描述
3. 会
4. 请具体描述

**Comment by Mottoi** [comment]
2。规定头图大小 自动裁剪为指定大小
4.浏览器bug
