### ISSUE TITLE
评论框按钮点击后报错

### ISSUE THREAD

**Issue by w4ctech** [idawnlight/typecho-theme-material#55]
点击评论栏下的class为mdl-button__ripple-container的按钮控制台报错，报错信息为 ``Cannot read property 'parentNode' of null``
复现方法
![image](https://user-images.githubusercontent.com/33955669/46928232-2b854600-d06c-11e8-8ed7-ec9d1eb508f0.png)

![image](https://user-images.githubusercontent.com/33955669/46928204-085a9680-d06c-11e8-9505-90b83527e547.png)
![image](https://user-images.githubusercontent.com/33955669/46928212-101a3b00-d06c-11e8-995b-9cb2010b3214.png)

**Comment by idawnlight** [comment]
这是个已知 bug，似乎是 MDL 的历史遗留问题，因此不会被修复
