### ISSUE TITLE
Mathjax插件公式缩放被遮挡

### ISSUE THREAD

**Issue by ajcxsu** [idawnlight/typecho-theme-material#56]
版本：3.2.5
浏览器：Chrome 70.0.3538.67

![2018-10-26 15-51-37](https://user-images.githubusercontent.com/31349569/47552619-b4876180-d937-11e8-969b-add636281e8e.png)
![2018-10-26 15-51-57](https://user-images.githubusercontent.com/31349569/47552621-b4876180-d937-11e8-80e5-b8dd31f3797e.png)

**Comment by idawnlight** [comment]
是 `#post-content p` 的 `overflow: none`  的问题
