### ISSUE TITLE
建议增加标签云部分和友链部分

### ISSUE THREAD

**Issue by scwlt30** [idawnlight/typecho-theme-material#65]
您的主题感觉是社区里最好看的，但我觉得可以加一个标签云，友联和留言板

**Comment by idawnlight** [comment]
标签云会考虑，目前不知道怎么写比较好
友链有，请仔细阅读 README
留言板直接创建空白页面即可

**Comment by monsterxcn** [comment]
自荐[这里](https://monsterx.cn/tags.html)的标签云样式 23333 。参考 Hexo-Theme-Spectre 改的，一个跟 Hexo-Theme-Material 蛮像的主题。可能还少的一点功能就是根据标签下文章数目给标签设定大小啥的。菜鸡自改，仅供参考啦 233 ...

**Comment by idawnlight** [comment]
@monsterxcn PR，请（

**Comment by monsterxcn** [comment]
Emmmm 大佬请看一哈我 pr 的姿势有木有什么问题。我先逃了哈哈哈

**Comment by monsterxcn** [comment]
> @monsterxcn PR，请（

Emmmm 大佬请看一哈我 pr 的姿势有木有什么问题。我先逃了哈哈哈

**Comment by scwlt30** [comment]
感谢巨佬，您看看WP-Cumulus如何，就是黄学长博客那个球

**Comment by scwlt30** [comment]
还有，我是小白，请问如何加快背景图的加载速度，感觉每次进后面背景都加载的贼慢qwq

**Comment by idawnlight** [comment]
@scwlt30 WP-Cumulus 作为部件还好，作为独立的标签云就不合适了，但是显然现在没地方放这个组件（
背景图尽量小点，找个快点的图床，其他好像也没什么办法了...

**Comment by scwlt30** [comment]
ok谢谢

**Comment by stevenjoezhang** [comment]
那个似乎用的是flash？应该能找到html5实现的轮子

**Comment by ZigZagK** [comment]
@scwlt30 @stevenjoezhang [tagcanvas](http://www.goat1000.com/tagcanvas.php) HTML5实现的轮子![](https://zigzagk.top/usr/themes/MDUI2333/img/QAQ/tieba/9.png)

**Comment by MineOlym** [comment]
markdown的编辑器怎么更新呢 换行有点不兼容 以及最新的Markdown写的表格在网站里显示不出来效果
