### ISSUE TITLE
页脚的问题

### ISSUE THREAD

**Issue by hisme-spoon** [idawnlight/typecho-theme-material#72]
底部白色的页脚，当本页长度没有一个屏幕那么长的时候不会处在底部

**Comment by NagaseIori** [comment]
issue为什么加上了wontfix标签？使用了这个主题有几年了，问题一直存在，也确实比较影响美观。

**Comment by idawnlight** [comment]
> issue为什么加上了wontfix标签？使用了这个主题有几年了，问题一直存在，也确实比较影响美观。

本项目是 [iblh/hexo-theme-material](https://github.com/iblh/hexo-theme-material) 的移植版本，在维护初期选择与上游保持一致，这一问题在上游中也一直存在，直至终止维护也没有解决。

目前，上游项目与使用的组件库已于数年前终止维护，难以继续开发，因此本项目当前仅考虑修复遗留的 bug 与兼容性问题，不对样式作额外改动或新增功能。若有能力，也欢迎尝试自行解决后提出 Pull Request。
