### ISSUE TITLE
重大BUG

### ISSUE THREAD

**Issue by mkx1269173252** [idawnlight/typecho-theme-material#77]
滑动BUG:
https://s2.ax1x.com/2019/06/04/VtAwQg.png
移动端BUG:
https://s2.ax1x.com/2019/06/04/VtAyoq.jpg
https://s2.ax1x.com/2019/06/04/VtAcF0.jpg

**Comment by idawnlight** [comment]
对于所谓“滑动BUG”，请禁用“平滑滚动效果”，这是一个旧式脚本并在目前不被建议使用。
对于所谓“移动端BUG”，我的博客为极致加载速度默认不通过第三方源加载 Material Icons，请自行在自己的博客中启用，同时建议您更新您的 Android 设备并使用现代浏览器。
