### ISSUE TITLE
建议在这里可以使用API

### ISSUE THREAD

**Issue by dyl8023** [idawnlight/typecho-theme-material#81]
建议在首页顶部左边标语可以使用API
![Lily_Screenshot_1562579363](https://user-images.githubusercontent.com/52656767/60801064-e16b6400-a1a8-11e9-841c-487689890aef.png)

这样就可以使用那种每日一言啊什么的 希望可以更新这个功能

**Comment by bbaa-bbaa** [comment]
其实实现各种api的适配也挺麻烦的，毕竟这种api没有一种标准
那里可以填写script标签来实现对一言api的使用
方法可以自行实现~
比如在哪里可以直接填写`<script type="text/javascript" src="https://api.lwl12.com/hitokoto/v1?encode=js&charset=utf-8"></script><span id="lwlhitokoto"><script>lwlhitokoto()</script></span>`
来实现对[lwl12 API](https://blog.lwl12.com/read/hitokoto-api.html)的引用

**Comment by bbaa-bbaa** [comment]
`<script src="https://v1.hitokoto.cn/?c=f&encode=js&select=%23main%20%3E%20div.material-index.mdl-grid%20%3E%20div.mdl-card.mdl-shadow--2dp.daily-pic.mdl-cell.mdl-cell--8-col.index-top-block%20%3E%20div.mdl-card__media.mdl-color-text--grey-50%20%3E%20p%20%3E%20a" defer></script>`
填写上面代码可以实现对你说的批评的引用

**Comment by dyl8023** [comment]
感谢！

**Comment by idawnlight** [comment]
那解决了是不是可以关 issue 了（

**Comment by bbaa-bbaa** [comment]
> 那解决了是不是可以关 issue 了（

把#82也关了吧

**Comment by w4ctech** [comment]
> 其实实现各种api的适配也挺麻烦的，毕竟这种api没有一种标准
> 那里可以填写script标签来实现对一言api的使用
> 方法可以自行实现~
> 比如在哪里可以直接填写`<script type="text/javascript" src="https://api.lwl12.com/hitokoto/v1?encode=js&charset=utf-8"></script><span id="lwlhitokoto"><script>lwlhitokoto()</script></span>`
> 来实现对[lwl12 API](https://blog.lwl12.com/read/hitokoto-api.html)的引用

感谢大佬。

**Comment by dyl8023** [comment]
> 其实实现各种api的适配也挺麻烦的，毕竟这种api没有一种标准
> 那里可以填写脚本标签来实现对一言api的使用
> 方法可以自行实现~
> 比如在哪里可以直接填写`<script type="text/javascript" src="https://api.lwl12.com/hitokoto/v1?encode=js&charset=utf-8"></script><span id="lwlhitokoto"><script>lwlhitokoto()</script></span>`
> 来实现对[lwl 12 API](https://blog.lwl12.com/read/hitokoto-api.html)的引用



> `<script src="https://v1.hitokoto.cn/?c=f&encode=js&select=%23main%20%3E%20div.material-index.mdl-grid%20%3E%20div.mdl-card.mdl-shadow--2dp.daily-pic.mdl-cell.mdl-cell--8-col.index-top-block%20%3E%20div.mdl-card__media.mdl-color-text--grey-50%20%3E%20p%20%3E%20a" defer></script>`
> 填写上面代码可以实现对你说的api的引用

非常感谢
