### ISSUE TITLE
首页顶部的昵称不见了

### ISSUE THREAD

**Issue by dyl8023** [idawnlight/typecho-theme-material#83]
![Lily_Screenshot_1562602458](https://user-images.githubusercontent.com/52656767/60825609-abe16d80-a1de-11e9-8c7f-0a73d3faccb6.png)

就刚刚打开网站就看不到了。。之前还有的没有改什么东西

**Comment by idawnlight** [comment]
我不知道你做了什么，所以我没法解决你的问题

**Comment by dyl8023** [comment]
> 我不知道你做了什么，所以我没法解决你的问题

我把整个typecho重装了一次也没用，一开始还有然后等一两个小时没看就没了。。

**Comment by idawnlight** [comment]
@dyl8023 请提供一下你博客的链接

**Comment by dyl8023** [comment]
> @dyl8023 请提供一下你博客的链接

http://52mxg.cn/

**Comment by idawnlight** [comment]
> > @dyl8023 请提供一下你博客的链接
> 
> http://52mxg.cn/

请发布至少一篇文章，此字段根据第一篇文章作者判断

**Comment by dyl8023** [comment]
> > > @dyl8023 请提供一下你博客的链接
> > 
> > 
> > http://52mxg.cn/
> 
> 请发布至少一篇文章，此字段根据第一篇文章作者判断

好的 感谢！~
