### ISSUE TITLE
友链我启用了 并在新页面选用了模板

### ISSUE THREAD

**Issue by solikear** [idawnlight/typecho-theme-material#84]
deer404.top
并不显示

**Comment by idawnlight** [comment]
请**仔细阅读 README** 并启用相应插件

**Comment by solikear** [comment]
仔细阅读了 并启用了 数据库里有这个表 页面模板也选择了 就是不显示 
http://deer404.top/link.html

**Comment by idawnlight** [comment]
> 
> 
> 仔细阅读了 并启用了 数据库里有这个表 页面模板也选择了 就是不显示
> http://deer404.top/link.html

请确认已在控制台添加链接（管理->友情链接）

**Comment by solikear** [comment]
谢谢你
