### ISSUE TITLE
后台Roboto字体镜像设置失效

### ISSUE THREAD

**Issue by SmRiley** [idawnlight/typecho-theme-material#86]
RT,即使设置了第一项使用镜像,前台加载依然会使用谷歌字体,导致国内主机加载缓慢,十分影响访问速度.
![image](https://user-images.githubusercontent.com/45205313/72055875-86a4f780-3306-11ea-8c9b-d39785798298.png)
![image](https://user-images.githubusercontent.com/45205313/72055918-9d4b4e80-3306-11ea-8cb1-6d93510cf1e0.png)

**Comment by idawnlight** [comment]
看了一下，是中科大的 `fonts.proxy.ustclug.org` 跳转到了 `fonts.googleapis.com`，并不是主题的锅。印象中好像已经停止服务多时了，但是忘了移除...
事实上因为 Google Fonts 会根据 UA 自动调整载入的字体格式，并且存在访问限流，大部分镜像都不能正常工作，因此并不推荐使用镜像。以上两个镜像选项将在之后的版本中被移除。
目前中国大陆如果使用正确的 DNS，是可以解析到 Google 中国的数据中心的，调用官方源在大多数情况下都没有问题。
感谢反馈。

<img width="1042" alt="图片" src="https://user-images.githubusercontent.com/18070833/72078101-70616080-3333-11ea-8745-dc203ed471bc.png">
