### ISSUE TITLE
打开smoothscroll之后chrome控制台一直提示错误

### ISSUE THREAD

**Issue by goxofy** [idawnlight/typecho-theme-material#89]
![image](https://user-images.githubusercontent.com/1695416/74794450-35712600-52fe-11ea-8276-68d3f2d0224a.png)

鼠标滚轮每滑动一次会提示一个错误

**Comment by idawnlight** [comment]
此问题已在 #87 中被修正。

**Comment by goxofy** [comment]
谢谢！
