### ISSUE TITLE
能否添加图片浮层功能?

### ISSUE THREAD

**Issue by SmRiley** [idawnlight/typecho-theme-material#92]
之前一直用的是这个图片浮层插件https://www.yzmb.me/archives/net/highslide-for-typecho ,但是在最近某次主题更新后发现插件没效果了.问了一下插件作者,这是他的回复
![image](https://user-images.githubusercontent.com/45205313/76754580-56258200-67bd-11ea-8126-7ebf57c1ec01.png)
所以请问能否添加这个功能?

**Comment by idawnlight** [comment]
我本地测试这个插件没有任何问题，把插件的「弹窗模式」勾选「全部图片」看看

![图片](https://user-images.githubusercontent.com/18070833/76755193-668a2c80-67be-11ea-8fc2-8188344a4cfd.png)

![图片](https://user-images.githubusercontent.com/18070833/76755263-86215500-67be-11ea-9e33-ac6439ba439a.png)

**Comment by SmRiley** [comment]
感谢回复,排查后发现原因在于Markdown 编辑器接管了前台解析,导致插件失效.与主题无关.
