### ISSUE TITLE
无法引用友链模板

### ISSUE THREAD

**Issue by misaka10843** [idawnlight/typecho-theme-material#96]
我在TE插件仓库和typecho.me中下载了关键词为"友链""友情链接""link"的所有插件都无法显示在友链模板中，希望能说明友链的插件名或者相对应的网络地址

**Comment by idawnlight** [comment]
请仔细阅读 README。

[https://github.com/idawnlight/typecho-links-material](https://github.com/idawnlight/typecho-links-material)
