### ISSUE TITLE
mokejay的pixiv挂件挂了

### ISSUE THREAD

**Issue by feiwujia** [idawnlight/typecho-theme-material#97]
如题QAQ

**Comment by idawnlight** [comment]
我觉得这个问题直接反馈给 @mokeyjay 比较好，你反馈给我我也没法处理啊（

![image](https://user-images.githubusercontent.com/18070833/100243076-77578880-2f70-11eb-82ee-d3ec7df76e31.jpeg)

**Comment by mokeyjay** [comment]
@feiwujia 已修复。不知道为啥目录权限错了😅

**Comment by feiwujia** [comment]
感谢大佬！
